import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import 'remixicon/fonts/remixicon.css';

const fontJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "AGENCY WEB",
  description: "Generated by Giogi",
  icons: {
    icon: '/favicon.jpg',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontJakarta.className} antialiased`}>
        <Navbar />
        <div className="w-full">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
