import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import 'remixicon/fonts/remixicon.css';

const fontPoppins = Poppins ({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
})

export const metadata = {
  title: "AGENCY WEB",
  description: "Generated by Giogi",
  icons: {
    icon:'/favicon.jpg',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontPoppins.className} antialiased`}
      >
        <Navbar />
        <div className="container mx-auto px-4">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
