import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css';
import ClientLayout from "./ClientLayout";

const fontJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "AGENCY WEB",
  description: "Generated by Giogi",
  icons: {
    icon: '/favicon.jpg',
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontJakarta.className} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
